// commonJS, every file is module  (by default)
// Modules - Encapsulated code (only share minimum)
//const names = require('./4-names')
const {john,peter} = require('./4-names')
const sayHi = require('./5-utils')
const data = require('./6-alternative-flavour')
//sayHi('susan')
//sayHi(names.john)
//sayHi(names.peter)
require('./7-mind-grenade')
sayHi(john)
sayHi(peter)

console.log(data)